# Learn about building .NET container images:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source
ENV ASPNETCORE_URLS=http://+:8080

# copy csproj and restore as distinct layers
COPY ContosoPizza/*.csproj .
RUN dotnet restore  

# copy everything else and build app
COPY ContosoPizza/. .
RUN dotnet publish --os linux --arch x64 -c release -o /app


# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "ContosoPizza.dll"]